- exchange_calendars/xkls_holidays.py
@gerrymanoim , I am new to GitHub but would like to do my part.
I updated the xkls_holidays.py for Wesak day holiday from 2021 to 2024. Source is https://publicholidays.com.my/wesak-day/
> Update Wesak Day Holidays for 2021 to 2024

- exchange_calendars/exchange_calendar.py
- tests/test_exchange_calendar.py
Fixes issue #13.
Raise ValueError if `direction` is 'previous' and `dt` is earlier than first calendar minute.
> ENH: .minute_to_session_label out-of-bounds error handling

- exchange_calendars/common_holidays.py
- exchange_calendars/exchange_calendar_cmes.py
- exchange_calendars/exchange_calendar_xbog.py
Fixes FutureWarning when instantiating `XBOGExchangeCalendar`:  
* ``FutureWarning: DateOffset.__call__ is deprecated and will be removed in a future version.  Use `offset + other` instead.``
Changes CMESExchangeCalendar name from alias name "CME" to canonical name "CMES".
> Fix XBOG FutureWarning

- exchange_calendars/calendar_helpers.py
- exchange_calendars/exchange_calendar.py
> BUG: Fix errors / warnings related to pandas 1.3.0

- .github/dependabot.yml
I _think_ the name actually needs to be `requirements.txt`. If so, will change around the CI in a follow up PR.
> BLD: See if dependabot can manage requirement bumps

- .github/dependabot.yml
Dependabot cannot be made to look at a single file (only a single directory). For now, I'd like to keep the older lock file around, but aggressively update the newer one. Will think about a better way to do this.
> BLD: Revert dependabot change

- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_asex.py
- exchange_calendars/exchange_calendar_bvmf.py
- exchange_calendars/exchange_calendar_iepa.py
- exchange_calendars/exchange_calendar_xasx.py
- exchange_calendars/exchange_calendar_xdub.py
- exchange_calendars/exchange_calendar_xetr.py
- exchange_calendars/exchange_calendar_xfra.py
- exchange_calendars/exchange_calendar_xhkg.py
- exchange_calendars/exchange_calendar_xist.py
- exchange_calendars/exchange_calendar_xjse.py
- exchange_calendars/exchange_calendar_xkls.py
- exchange_calendars/exchange_calendar_xlim.py
- exchange_calendars/exchange_calendar_xlon.py
- exchange_calendars/exchange_calendar_xmex.py
- exchange_calendars/exchange_calendar_xmos.py
- exchange_calendars/exchange_calendar_xnze.py
- exchange_calendars/exchange_calendar_xpra.py
- exchange_calendars/exchange_calendar_xsgo.py
- exchange_calendars/exchange_calendar_xtae.py
- exchange_calendars/exchange_calendar_xtse.py
- exchange_calendars/exchange_calendar_xwar.py
- exchange_calendars/us_holidays.py
- exchange_calendars/xbkk_holidays.py
- tests/test_exchange_calendar.py
NB. Vast majority of changes relate to regularizing timezone of adhoc_holiday dates (23431fe1117be4ef2a24787b493c302979972493)
Fixes #33 by allowing special closes / opens to be defined for dates that are holidays and then filtering out these conflicts in `ExchangeCalendar._special_dates`
Regularizes `adhoc_holiday` dates as tz-naive (previously a mix of tz-naive, "UTC", "Asia/Jerusalem" and defined on one calendar as list of Holiday instances).
> Fix conflict between holidays and special dates

- exchange_calendars/calendar_utils.py
- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_aixk.py
- exchange_calendars/exchange_calendar_xhkg.py
- exchange_calendars/exchange_calendar_xkrx.py
- exchange_calendars/exchange_calendar_xtks.py
- exchange_calendars/precomputed_exchange_calendar.py
- exchange_calendars/us_futures_calendar.py
- tests/test_aixk_calendar.py
- tests/test_always_open.py
- tests/test_calendar_dispatcher.py
- tests/test_exchange_calendar.py
- tests/test_weekday_calendar.py
- tests/test_xbom_calendar.py
- tests/test_xhkg_calendar.py
- tests/test_xist_calendar.py
- tests/test_xkls_calendar.py
- tests/test_xkrx_calendar.py
- tests/test_xnys_calendar.py
- tests/test_xses_calendar.py
- tests/test_xshg_calendar.py
- tests/test_xtae_calendar.py
- tests/test_xtks_calendar.py
(re-submission of PR #37 with commit history re-aligned to master)
Partially covers #31 by exposing ExchangeCalendar kwargs via get_calendar.
Cache maintained on basis:
* only one copy of any calendar is cached.
* cached copy will be returned if calendar is requested with start and end dates that parse to the same values as those for which the cached version was created. Otherwise cached copy is overwritten with newly created calendar.
@GerryManoim, could I ask that you consider the appropriateness of the 'Notes' section that I've included to the ExchangeCalendar class documentation [here](https://github.com/gerrymanoim/exchange_calendars/pull/37/files#diff-ac7f6dd25cca9fe4be3305261ed8133284c3257c16b46bb27ace7d95c1c8f53cR113). Please offer any suggestions / revisions as you may see fit. …
> ENH: Expose calendar kwargs and handle out-of-bounds

- exchange_calendars/calendar_helpers.py
- exchange_calendars/calendar_utils.py
- exchange_calendars/errors.py
- exchange_calendars/exchange_calendar.py
- tests/test_calendar_helpers.py
Introduces Date and Minute types to define nature of parameters
and distinguish Date from existing Session type.
Refactors `parse_session` to distinguish `parse_timestamp`, `parse_date`
`parse_date` and `parse_session`.
Introduces errors `DateOutOfBounds` and `MinuteOutOfBounds`.
Overhauls parsing tests on `test_calendar_helpers.py`.
Introduces `ExchangeCalendar` methods `first_trading_minute` and
`last_trading_minute`.
---
Anticipated that the introduced ExchangeCalendar methods `first_trading_minute` and `last_trading_minute` will diverge from `first_session_open` and `last_session_close` on any introduction of a 'side' option to define trading minutes at session bounds. For now only distinction is that the new methods return as UTC.
> Improve parsing

- exchange_calendars/exchange_calendar_asex.py
As per https://en.wikipedia.org/wiki/Public_holidays_in_Greece, the two national holidays that appear in the exchange calendar for ASEX have proper names. This PR changes the generic names like `National Holiday 1` to the proper names from the Wikipedia page.
> Use proper names for ASEX national holidays.

- exchange_calendars/exchange_calendar_xbud.py
Fix an issue where the four-day-weekend rule for XBUD creates two holidays on the same day, i.e. 25 December, when the Second Day of Christmas, i.e. 26 December, falls onto a Tuesday.
The reason was that the regular four-day-weekend rule was applied for the Second Day of Christmas also when it was falling onto a Tuesday. Thus, the previous Monday became a holiday, but since it was already declared separately as a holiday, this created two holidays on the same day (with different names). The way unit tests are structured, this duplication was apparently not caught.
For examples where this change becomes visible, have a look at the years 2017 and 2023.
P.S.: Also re-named the national holidays to `National Day` as per [Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_Hungary).
> Fix XBUD Christmas holiday observances.

- tests/test_always_open.py
- tests/test_cmes_calendar.py
- tests/test_exchange_calendar.py
- tests/test_weekday_calendar.py
- tests/test_xhkg_calendar.py
- tests/test_xlon_calendar.py
Migrates following test modules to new test base:
test_always_open.py
test_weekday_calendar.py
test_xlon_calendar.py
test_xhkg_calendar.py
test_cmes_calendar.py
Also:
adds properties to Answers.
Renames `ExchangeCalendarTestBaseProposal` as
`ExchangeCalendarTestBaseNew`.
> Migrate to new test base, 0

- tests/test_aixk_calendar.py
- tests/test_asex_calendar.py
- tests/test_bvmf_calendar.py
- tests/test_cmes_calendar.py
- tests/test_exchange_calendar.py
- tests/test_iepa_calendar.py
- tests/test_xasx_calendar.py
(@gerrymanoim, this comment explains why for all calendars some new calendar-specific tests will be showing up as skipped.)
This PR extends work started by #91 to offer a **common implementation of common calendar-specific tests**...
Fixtures dedicated to these tests are defined on the base and can be optionally overriden by a subclass. If such a fixture is overriden then an associated test is executed with input as yielded by the fixture.
Fixture  |  Test
-|-
`regular_holidays_sample`  |  `test_regular_holidays_sample`
`adhoc_holidays_sample`  |  `test_adhoc_holidays_sample`
`non_holidays_sample`  |  `test_non_holidays_sample` 
`late_opens_sample`  |  `test_late_opens_sample`
`early_closes_sample`  |  `test_early_closes_sample`
`early_closes_sample_time`  | …
> Revise / Extend `ExchangeCalendarTestBaseNew`

- exchange_calendars/us_futures_calendar.py
Removes `QuantopianUSFuturesCalendar.default_start` which was unnecessarily earlier than the global start default. #112
> Remove `QuantopianUSFuturesCalendar.default_start`

- etc/factory_bounds.py
@gerrymanoim, I wrote this module months back to query the start and end bounds for which a calendar factory can instantiate a calendar without raising an error. It evalutes the bounds for a/all factories and the errors raised.
There's no current need for it although I had it lingering locally and rather than ditch it I thought to leave it in `/etc` for possible future utility.
If you don't see any utility in holding on to it, just let me know and I'll close without merging.
> Add `factory_bounds.py` to /etc

- etc/requirements_locked.txt
- exchange_calendars/pandas_extensions/offsets.py
- exchange_calendars/tase_holidays.py
- tests/test_exchange_calendar.py
Turns out the windows CI doesn't respect `PIP_CONSTRAINT` so it started failing when pandas/numpy got updated. 
This bumps everything in requirements_locked.txt to the newest version and fixes the resulting test failures. 
Need to come up with a better dependabot based workflow for these.
> TST: bump pandas and fix resulting test failures

- exchange_calendars/pandas_extensions/korean_holiday.py
- tests/test_xkrx_calendar.py
This PR addresses a bug in `exchange_calendars/pandas_extensions/korean_holiday.py`. You can see the bug by adding the following test case to `tests/test_xkrx_calendar.py`:
```python
def test_feb_29_2022_in_lunar_calendar(self, default_calendar):
default_calendar.regular_holidays.holidays(date(2022, 3, 31), date(2022, 3, 31))
```
The underlying cause is that `korean_holiday.py` is trying to store lunar dates inside Gregorian date objects. 2022-03-31 (Gregorian) corresponds to 2022-02-29 (Korean Lunar), at least according to https://astro.kasi.re.kr/life/pageView/8 (with Google Translate). 2022-02-29 is not a valid Gregorian date, and so the operation fails. This PR widens the date range used in `_reference_dates` if necessary, and then filters out any extra holidays at the end.
As an …
> Attempt to fix Korean lunar calendar bug.

- .gitignore
- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_xkrx.py
- setup.py
- tests/test_exchange_calendar.py
Extends documentation and adds type annotations to `ExchangeCalendar` "calendar-definition" properties.
Moves 'special offsets' implementation from `ExchangeCalendar` to `XKRXExchangeCalendar` (leaving a `apply_special_offsets` hook into the `ExchangeCalendar` constructor). The implementation added a fair bit of bulk to `ExchangeCalendar` although is used only by `XKRXExchangeCalendar`. Given that no other calendar uses it, and that it's anticipated `XKRXExchangeCalendar` will move to hardcoded dates anyway (#128), this PR explicitly makes the implementation specific to `XKRXExchangeCalendar`.
Also
- a little general linting.
- tried to add 'black' to dev environment, reverted due to pip conflicts.
> Add doc + types and moves 'special offsets' implementation to XKRX

- .github/workflows/main.yml
- exchange_calendars/calendar_helpers.py
- exchange_calendars/errors.py
- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_aixk.py
- exchange_calendars/exchange_calendar_xdub.py
- exchange_calendars/exchange_calendar_xhkg.py
- exchange_calendars/exchange_calendar_xist.py
- exchange_calendars/exchange_calendar_xkls.py
- exchange_calendars/exchange_calendar_xkrx.py
- exchange_calendars/exchange_calendar_xnys.py
- exchange_calendars/exchange_calendar_xshg.py
- exchange_calendars/exchange_calendar_xtks.py
- exchange_calendars/lunisolar_holidays.py
- exchange_calendars/precomputed_exchange_calendar.py
- exchange_calendars/utils/pandas_utils.py
- exchange_calendars/xkrx_holidays.py
- tests/test_always_open.py
- tests/test_asex_calendar.py
- tests/test_calendar_dispatcher.py
- tests/test_calendar_helpers.py
- tests/test_exchange_calendar.py
- tests/test_utils.py
- tests/test_weekday_calendar.py
- tests/test_xsgo_calendar.py
Changes sessions to tz-naive.
Changes schedule times to UTC.
Also
- Adds typing to, adds doc to and renames parameters of:
- some private `ExchangeCalendar` initialization methods.
- some private `XKRXExchangeCalendar` initialization methods.
- `pandas_utils.days_at_time`.
Change discussed in #42.
Contributes to v4 #61.
> Change sessions to tz-naive, times to UTC

- docs/tutorials/trading_index.ipynb
- exchange_calendars/calendar_helpers.py
- exchange_calendars/exchange_calendar.py
- exchange_calendars/utils/pandas_utils.py
- setup.cfg
- tests/test_calendar_helpers.py
- tests/test_exchange_calendar.py
v4 development (#61).
* Fixes warnings.
* Updates `ExchangeCalendar.trading_index` and `calendar_helpers._TradingIndex`.
See commit messages for more further details.
> v4 dev: fix warnings and update trading index

- .pre-commit-config.yaml
- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_aixk.py
- exchange_calendars/exchange_calendar_xbom.py
- exchange_calendars/exchange_calendar_xhkg.py
- exchange_calendars/exchange_calendar_xkrx.py
- exchange_calendars/exchange_calendar_xses.py
- exchange_calendars/exchange_calendar_xshg.py
- exchange_calendars/exchange_calendar_xtks.py
- exchange_calendars/precomputed_exchange_calendar.py
- tests/test_exchange_calendar.py
v4 development (#61):
- Revises `ExchangeCalendar.*_window` methods to return windows of length `count` (instead of `count` + 1).
- Changes error raised when prev/next minute/session is out-of-bounds (now raises `Requested*OutOfBounds`).
- Changes `ExchangeCalendar` `bound*` and `default*` properties to class methods (related to #182).
> v4 dev: revises ` *window`, `bound*`, `default*` and prev/next session/minute methods.

- exchange_calendars/exchange_calendar.py
- setup.cfg
- tests/test_calendar_helpers.py
- tests/test_exchange_calendar.py
v4 development (#61)
Changes default calendar side to "left" for all calendars (from "right" for 24h calendars and "both" for all others) (#181).
Selective linting of `exchange_calendar.py` (using mypy and pylint) post v4 changes.
> v4 dev: Change default `side` to "left" and post v4 linting

- exchange_calendars/ecal.py
ecal CLI command gets ValueError because it uses timezone aware date.
Removed UTC.
> ecal should use timezone naive date

- etc/make_exchange_calendar_test_csv.py
`exchange_calendars` v4 made session labels timezone-naive. This PR fixes `etc/make_exchange_calendar_test_csv.py`, which currently fails when requesting calendars with date ranges taken from the existing output, because they have an explicit timezone set.
> Fix etc/make_exchange_calendar_test_csv.py

- .github/workflows/release.yml
Reverts release workflow to pass --extra-index-url in order that pip can locate dependencies.
> Revert (partially) release workflow

- exchange_calendars/exchange_calendar_xist.py
- tests/test_xist_calendar.py
Added the days that the exchange is now closed as ad-hoc holidays; see [Bloomberg article](https://www.bloomberg.com/news/articles/2023-02-08/turkey-suspends-trading-in-stock-market-as-rout-deepened).
This closes #283.
> Add ad-hoc holidays for XIST trading suspension due to earthquake.

- exchange_calendars/calendar_utils.py
Add a `XNAS` alias that represents NASDAQ which has the same calendar as XNYS. The `XNAS` mic is a common representation for NASDAQ: see e.g: https://en.wikipedia.org/wiki/Market_Identifier_Code and http://www.iotafinance.com/en/Overview-operating-MIC-code-XNAS.html
> Add XNAS calendar alias

- etc/requirements.txt
- etc/requirements_dev.txt
- etc/requirements_minpandas.txt
- exchange_calendars/exchange_calendar.py
- exchange_calendars/exchange_calendar_xbud.py
- exchange_calendars/exchange_calendar_xbue.py
- exchange_calendars/exchange_calendar_xmos.py
- exchange_calendars/exchange_calendar_xphs.py
- exchange_calendars/exchange_calendar_xsgo.py
- exchange_calendars/exchange_calendar_xtai.py
- exchange_calendars/exchange_calendar_xwar.py
- exchange_calendars/xbkk_holidays.py
- tests/test_calendar_helpers.py
- tests/test_exchange_calendar.py
Updates dependencies including pandas from 2.0.3 to 2.1.0.
The pandas update has introduced a bug and some warnings that have necessitated changes (more changes in fact that than the move from pandas 1.5 to 2.0!).
- Fixes #326 - updates functions passed to `Holiday` observance option. These functions now all take a `datetime.datetime`, never a `pandas.DatetimeIndex`.
- This required notable changes to the XBUD and XTAI modules which both relied on previously being able to, effectively, observe a single holiday on multiple days (this provided for adding an extra holiday on a Friday/Monday when the official holiday fell on a Thursday/Tuesday and the extra day's holiday is stipulated to bridge the weekend and the official holiday). This is no longer an option, such that these 'bridge' days …
> Updates for pandas 2.1.0

- exchange_calendars/exchange_calendar_xbom.py
In 2008, the timezone identifier Asia/Calcutta was renamed to
Asia/Kolkata due to the widespread adoption of the new city name over
the old one.
While the Asia/Calcutta alias still points to the Asia/Kolkata timezone,
it's worth noting that Debian unstable has relocated this alias to the
tzdata-legacy package, which is not included in the default
installation.
To ensure compatibility and consistency, it is recommended to use
Asia/Kolkata directly rather than relying on the Asia/Calcutta alias.
This change aligns with the current naming conventions.
> Rename Asia/Calcutta to Asia/Kolkata

- tests/test_xsgo_calendar.py
There is a dangling equality check in the tests here that looks like it should be an assertion.
> TST: Fix missing assertion in XSGO calendar tests

- exchange_calendars/pandas_extensions/holiday.py
I don't think anything is actually using this, so hasn't tripped over it yet, but there is what looks like a "copy/pasta" bug in `holidays.py` that this fixes around handling of the range when the TZ is only specified on the end date. There is a missing assertion for matching start and end date timezones, too (there is currently what ruff calls a "pointless equality check" whose result is not checked).
> BUG: Fix end-date-only TZ logic in holiday.py

- exchange_calendars/exchange_calendar_bvmf.py
On December 22nd, 2023, a new law was passed in Brazil, where Black Awareness Day became a national holiday, starting in 2024. Brazilian exchange "B3" (formerly known as BVMF), has already implemented the new calendar.
> feat: added new national holiday to BVMF calendar

- exchange_calendars/exchange_calendar_xdub.py
Closes: #383 
Whilst it looks correct that there is no Early May Bank Holiday for Euronext Dublin in 2019 and 2020, it does seem to have been reacted from 2021 onwards. See screenshots below of excerpts from the Euronext website:
Euronext 2019 - no May Bank (https://web.archive.org/web/20190708142940/https://www.euronext.com/en/trade/trading-hours-holidays): 
Euronext 2020 - no May Bank (https://web.archive.org/web/20200904035212/https://www.euronext.com/en/trade/trading-hours-holidays):
Euronext 2021 - May Bank (https://www.euronext.com/en/trade/trading-hours-holidays):
and on that same page you can see calendars for 2021 onwards, all of which have the early May Bank Holiday.
------------------
**Workflow to add a new Exchange Calendar**
It's recommended that whilst working through the …
> XDUB: Add May bank holiday post-2021

- exchange_calendars/exchange_calendar_xetr.py
- exchange_calendars/exchange_calendar_xfra.py
- exchange_calendars/exchange_calendar_xnze.py
- tests/test_exchange_calendar.py
Hi all,
I noticed that some calendars use an incorrect or dubious timezone info. Specifically, XETR and XFRA use `ZoneInfo('CET')` and XNZE uses `ZoneInfo('NZ')`.
Re XETR and XFRA, I think it's incorrect to use CET since this is a standard time, i.e. a fixed offset (+01:00) to UTC. But since Germany observes summer time (CEST = +02:00), the correct timezone to use would be `ZoneInfo('Europe/Berlin')`.
For XNZE, I'm not even sure what the definition of `ZoneInfo('NZ') is, but `ZoneInfo('Pacific/Auckland')` seems to be the correct time zone to use.
> BUG: Fix timezone names

- exchange_calendars/exchange_calendar_xbue.py
- exchange_calendars/exchange_calendar_xphs.py
Some calendars define ad-hoc holidays not as Pandas timestamps, but as strings. This may cause breaks as the interface mandates a list of Pandas timestamps.
> Ensure ad-hoc holidays are proper Pandas timestamps.

- .github/workflows/main.yml
- pyproject.toml
Changes test matrix to use 3.12 as opposed to 3.11.
> Bump supported python upper limit to 3.12

- tests/test_calendar_helpers.py
This commit replaces legacy time zone names (US/Eastern and US/Central)
with their current identifiers (America/New_York and America/Chicago)
across all tests.
Recent Debian distributions no longer include legacy time zone names in
the default installation, as they are moved to the tzdata-legacy
package. As a result, tests relying on these legacy names fail without
the tzdata-legacy package installed.
> Avoid using legacy time zone names in tests

- exchange_calendars/exchange_calendar_xdus.py
- exchange_calendars/exchange_calendar_xham.py
This commit replaces the legacy time zone name CET with the current name Europe/Brussels in two tests.
Release 2024b of the tz database removed System V symlinks including the symlink that points from CET to Europe/Brussels.
In Debian the CET symlink has moved from the tzdata package to tzdata-legacy.
See https://data.iana.org/time-zones/tzdb-2024b/NEWS and https://lists.debian.org/debian-devel-changes/2024/10/msg00256.html
> Avoid using legacy time zone name 'CET' in tests

- exchange_calendars/exchange_calendar_xnys.py
- exchange_calendars/us_holidays.py
- tests/test_xnys_calendar.py
Added Jimmy Carter Day of Mourning for XNYS, XCBF, CMES, and IEPA
Sources:
Nasdaq - https://www.nasdaq.com/press-release/nasdaq-announces-closure-its-us-markets-honor-national-day-mourning-former-president
ICE - https://ir.theice.com/press/news-details/2024/The-New-York-Stock-Exchange-Will-Close-Markets-on-January-9-to-Honor-the-Passing-of-Former-President-Jimmy-Carter-on-National-Day-of-Mourning/default.aspx
CME - https://www.cmegroup.com/media-room/press-releases/2025/12/30/cme_group_announcestradinghoursforusnationaldayofmourningtohonor.html
> Add Jimmy Carter Day of Mourning

- exchange_calendars/exchange_calendar_xsau.py
Fixes #444
Fixes error message for XSAU when pass an end date that is later than the max bound.
Fixes by removing superflous part of oob error messages, thereby reverting to default implementation.
> Fix XSAU `bound_max` error msg.

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- pyproject.toml
Bumps max Python version to 3.13.
Updates:
- workflows to use 3.13 (including upper version of test matrix).
- pyproject.toml project classifiers (as declared to PyPI).
> Bump max Python version to 3.13

- .devcontainer/Dockerfile
- .github/workflows/main.yml
- etc/make_exchange_calendar_test_csv.py
Use Python tzdata for consistent timezone data across platforms when running tests.
This PR includes the following changes (which only affect testing):
* Configure GitHub runners to use Python tzdata.
* Use Python tzdata in `etc/make_exchange_calendar_test_csv.py`.
* Use Python tzdata in the devcontainer.
Python tzdata is used as a fallback for systems that do not have system timezone data installed. By setting the PYTHONTZPATH environment variable, Python's tzdata package is used instead of the operating system's timezone data. This will prevent tests from failing due to changes that are beyond the control of this project, such as modifications to timezone data on a GitHub runner or differences on users' local machines.
Tests for the Philippine Stock Exchange (XPHS) are failing due to …
> Use Python tzdata in tests

- exchange_calendars/exchange_calendar.py
This change converts a couple of numpy bools and ints to true python bools (as the type signatures promise).
We do this elsewhere, but the coverage wasn't quite 100%.
> Return true bools, not numpy ints, etc.

- exchange_calendars/calendar_helpers.py
- tests/test_calendar_helpers.py
We are using exchange calendars but keep getting lint errors when we try to call methods like `ExchangeCalendar.sessions_in_range` with `datetime.date`s, which is a bit counter-intuitive. 
From my understanding the `Date` type alias is passed to `pd.Timestamp` for parsing, which is happy with `datetime.date`s. Could we please add it, in addition to `datetime.datetime`?
> Date type alias takes datetime.date
